export const STATE_REDUCER = "SETSTATE";
export const TRIGGER_REDUCER = "SETTRIGGER";
export const SNACKBAR_REDUCER = "SETSNACKBAR";
export const NOMINATE_REDUCER = "SETNOMINATE";
export const MOVIES_REDUCER = "SETMOVIES";